apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
          - --provider=github
          - --http-address=0.0.0.0:4180

          #  protect everything by making oauth2-proxy the front door
          - --upstream=http://flask-service.default.svc.cluster.local:80

          #  your domain
          - --redirect-url=https://mariam-flask.website/oauth2/callback
          - --whitelist-domain=mariam-flask.website

          #  cookies
          - --cookie-secure=true
          - --cookie-httponly=true
          - --cookie-samesite=lax

          
          - --email-domain=*
          - --set-authorization-header=true
          - --pass-access-token=true
          - --reverse-proxy=true
        env:
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: client-id
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: client-secret
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name: oauth2-proxy-secret
                key: cookie-secret
        ports:
          - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: default
spec:
  selector:
    app: oauth2-proxy
  ports:
    - name: http
      port: 4180
      targetPort: 4180